steps:

# build frontend
- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  args: ["install"]
#- name: 'buildkite/puppeteer'
#  dir: 'frontend'
#  args: ["npm", "run", "test:chrome:headless"]
# get environment.prod.ts
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'frontend/src/environments'
  entrypoint: 'bash'
  args: ["-c", "gsutil cp gs://$PROJECT_ID-env/environment.prod.ts environment.prod.ts"]
- name: 'gcr.io/cloud-builders/npm'
  dir: 'frontend'
  entrypoint: 'bash'
  args: ["-c", "npm run build:prod"]

# Deploy frontend service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  dir: 'frontend'
  args: ['-c', "gcloud app deploy app.yaml"]

# Deploy backend service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  dir: 'backend'
  args: ['-c', "sed -i 's/{PROJECT_ID}/'$PROJECT_ID'/g' app.yaml && gcloud app deploy app.yaml"]

# Deploy dispatch.yaml
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', "gcloud app deploy dispatch.yaml"]